//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManmagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssetMSMVCDBEntities7 : DbContext
    {
        public AssetMSMVCDBEntities7()
            : base("name=AssetMSMVCDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset_master> Asset_master { get; set; }
        public virtual DbSet<assetDef> assetDefs { get; set; }
        public virtual DbSet<assetType> assetTypes { get; set; }
        public virtual DbSet<logintbl> logintbls { get; set; }
        public virtual DbSet<PurchaseTbl> PurchaseTbls { get; set; }
        public virtual DbSet<userReg> userRegs { get; set; }
        public virtual DbSet<vendorTbl> vendorTbls { get; set; }
    }
}
