//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManmagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assetDef()
        {
            this.Asset_master = new HashSet<Asset_master>();
            this.PurchaseTbls = new HashSet<PurchaseTbl>();
        }
    
        public int ad_id { get; set; }
        public string ad_name { get; set; }
        public Nullable<int> ad_type_id { get; set; }
        public string ad_class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_master> Asset_master { get; set; }
        public virtual assetType assetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseTbl> PurchaseTbls { get; set; }
    }
}
