//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManmagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userReg
    {
        public int u_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public Nullable<decimal> phone_number { get; set; }
        public Nullable<int> l_id { get; set; }
    
        public virtual logintbl logintbl { get; set; }
    }
}
